# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: open_arms
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - open_arms_joint1
    - open_arms_joint2
    - open_arms_joint3
    - open_arms_joint4
    - open_arms_joint5
    - open_arms_joint6
    - open_arms_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
open_arms_controller:
  type: position_controllers/JointPositionController
  joints:
    - open_arms_joint1
    - open_arms_joint2
    - open_arms_joint3
    - open_arms_joint4
    - open_arms_joint5
    - open_arms_joint6
    - open_arms_joint7
  gains:
    open_arms_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    open_arms_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    open_arms_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    open_arms_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    open_arms_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    open_arms_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    open_arms_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1